# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zV7WBdHpn7aho7he_DnuAHCIQrtuw7vV
"""

approvedLeaves = [
{"emp_id": 1, "leaveFrom": 14-12-2020, "leaveUpto": 18-12-2020},
{"emp_id": 3, "leaveFrom": 22-12-2020, "leaveUpto": 24-12-2020},
{"emp_id": 7, "leaveFrom": 27-12-2020, "leaveUpto": 30-12-2020},


]



import time 
import datetime 
import numpy as np

def isSlotAvailable(approved_leaves, request_leaves):
    leaf = request_leaves['leaveFrom']
    leaf = list(map(int, leaf.split('-')))
    leaf = date(leaf[2],leaf[1] ,leaf[0]) 
    leat = request_leaves['leaveUpto']
    leat = list(map(int, leat.split('-')))
    leat = date(leat[2],leat[1] ,leat[0])
    
    for i in range(approved_leaves):
        f = i['leaveFrom']
        f = list(map(int, f.split('-')))
        t = i['leaveUpto']
        t = list(map(int, t.split('-')))
        x = date(f[2],f[1] ,f[0]) 
        y = date(t[2],t[1] ,t[0])
        if (x<=leaf<=y or x<=leat<=y):
            return False
    return True


def availableLeaveSlots(approvedLeaves, startDate, endDate):
     ans=[]
     for x in approvedLeaves:
        leave= time.mktime(datetime.datetime.strptime(x['leaveFrom'], 
                                                "%d/%m/%Y").timetuple())
        froms= time.mktime(datetime.datetime.strptime(x['leaveUpto'], 
                                                "%d/%m/%Y").timetuple())
        start= time.mktime(datetime.datetime.strptime(startDate, 
                                                "%d/%m/%Y").timetuple())
        end=  time.mktime(datetime.datetime.strptime(endDate, 
                                                "%d/%m/%Y").timetuple())
        tmp={}
        if(leave>=start and froms<=end):
            tmp['availableFrom']= leaveFrom
            tmp['availableUpto']= leaveUpto
        ans.append(tmp)
     return ans

